/*
  Auto-generated by Spline
*/
"use client"
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/ANstCNDFba0eEv82/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group
            name="flower"
            position={[194.31, 105.86, 64.23]}
            rotation={[0.22, -0.49, 1.62]}
            scale={[0.14, 0.69, 0.14]}
          >
            <mesh
              name="Subdiv 4"
              geometry={nodes['Subdiv 4'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[-47.57, -1.07, 47.51]}
              rotation={[-Math.PI / 2, 0, 2.36]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Subdiv 41"
              geometry={nodes['Subdiv 41'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[47.57, -1.07, -47.62]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Subdiv 3"
              geometry={nodes['Subdiv 3'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[-47.57, -1.07, -47.62]}
              rotation={[-Math.PI / 2, 0, Math.PI / 4]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Subdiv 31"
              geometry={nodes['Subdiv 31'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[47.57, -1.07, 47.51]}
              rotation={[-Math.PI / 2, 0, -2.36]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Subdiv 2"
              geometry={nodes['Subdiv 2'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[-67.27, -1.07, -0.05]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Subdiv 21"
              geometry={nodes['Subdiv 21'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[67.27, -1.07, -0.05]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Subdiv"
              geometry={nodes.Subdiv.geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[0, -1.07, 67.22]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Cube 4"
              geometry={nodes['Cube 4'].geometry}
              material={materials.Untitled}
              castShadow
              receiveShadow
              position={[0, -1.07, -67.33]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.1, 1, 0.38]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials.Hair}
              castShadow
              receiveShadow
              position={[-1.23, -1.51, 0.86]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-0.41, 0.41, 0.18]}
            />
          </group>
          <pointLight
            name="Point Light"
            castShadow
            intensity={4}
            decay={20}
            distance={4222}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={100}
            shadow-camera-far={2500}
            color="#ada3fe"
            position={[464.84, 290.22, -155.4]}
            scale={[1.43, 1, 1]}
          />
          <directionalLight
            name="Directional Light 2"
            castShadow
            intensity={0.9}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-3389.844}
            shadow-camera-right={3389.844}
            shadow-camera-top={3389.844}
            shadow-camera-bottom={-3389.844}
            color="#fee5dd"
            position={[-233.21, -574.18, 870.31]}
            rotation={[0, 0, -0.01]}
            scale={[1.43, 1, 1]}
          />
          <group name="Character" position={[117.08, -194.62, 71.35]} rotation={[0, -0.53, 0]} scale={[1.19, 1, 1.12]}>
            <group name="head" position={[-3.51, 279.42, -51.88]} rotation={[0.12, -0.01, -0.09]} scale={[1, 1, 0.62]}>
              <mesh
                name="Cube 15"
                geometry={nodes['Cube 15'].geometry}
                material={materials['Cube 15 Material']}
                castShadow
                receiveShadow
                position={[11.41, -1.05, 29.62]}
                rotation={[0, Math.PI / 9, 0]}
                scale={1}
              />
              <mesh
                name="Cube 14"
                geometry={nodes['Cube 14'].geometry}
                material={materials['Cube 14 Material']}
                castShadow
                receiveShadow
                position={[-19.76, -3.85, 29.71]}
                rotation={[0, -Math.PI / 9, 0]}
                scale={1}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Eyebrows}
                castShadow
                receiveShadow
                position={[12.6, 4.37, 31.35]}
                rotation={[-0.1, 0.28, 0.2]}
                scale={1}
              />
              <mesh
                name="Cube 12"
                geometry={nodes['Cube 12'].geometry}
                material={materials.Eyebrows}
                castShadow
                receiveShadow
                position={[-21.21, 1.91, 34.94]}
                rotation={[2.89, -0.25, 2.9]}
                scale={[-1, 1, 3.51]}
              />
              <mesh
                name="Ellipse 2"
                geometry={nodes['Ellipse 2'].geometry}
                material={materials['Ellipse 2 Material']}
                castShadow
                receiveShadow
                position={[-24.64, -21.51, 23.43]}
                rotation={[0.26, -0.58, 0]}
                scale={1}
              />
              <mesh
                name="Ellipse"
                geometry={nodes.Ellipse.geometry}
                material={materials['Ellipse Material']}
                castShadow
                receiveShadow
                position={[16.55, -20.69, 24.79]}
                rotation={[0.26, 0.56, 0]}
                scale={1}
              />
              <mesh
                name="Cube 9"
                geometry={nodes['Cube 9'].geometry}
                material={materials['Cube 9 Material']}
                castShadow
                receiveShadow
                position={[4.7, -31.2, 28.83]}
                rotation={[0.14, -0.46, -2.93]}
                scale={[0.93, 1, 0.67]}
              />
              <mesh
                name="Cube 2"
                geometry={nodes['Cube 2'].geometry}
                material={materials['Cube 2 Material']}
                castShadow
                receiveShadow
                position={[38.89, -9, -6.07]}
                scale={[-1, 1, 1]}
              />
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials['Cube1 Material']}
                castShadow
                receiveShadow
                position={[-46.02, -12.67, -6.07]}
              />
              <mesh
                name="hair"
                geometry={nodes.hair.geometry}
                material={materials['hair Material']}
                castShadow
                receiveShadow
                position={[-3.22, 43.62, -37.35]}
                rotation={[-Math.PI / 6, 0, 0]}
                scale={[1.04, 1, 1]}
              />
              <mesh
                name="Sphere 2"
                geometry={nodes['Sphere 2'].geometry}
                material={materials['Sphere 2 Material']}
                castShadow
                receiveShadow
                position={[-2.88, -8.51, -8.67]}
              />
            </group>
            <mesh
              name="Cube 17"
              geometry={nodes['Cube 17'].geometry}
              material={materials['Cube 17 Material']}
              castShadow
              receiveShadow
              position={[-2.19, 116.88, -71.94]}
              scale={[1, 1, 0.95]}
            />
            <mesh
              name="body"
              geometry={nodes.body.geometry}
              material={materials['body Material']}
              castShadow
              receiveShadow
              position={[-5.07, 112.17, -71.74]}
            />
            <group
              name="lower_part"
              position={[-7.95, -100.88, -73.33]}
              rotation={[0, 0.52, 0]}
              scale={[0.32, 0.48, 0.26]}
            >
              <mesh
                name="skirt"
                geometry={nodes.skirt.geometry}
                material={materials.Pants}
                castShadow
                receiveShadow
                position={[0, 233.46, 0]}
                scale={[1.78, 0.85, 1.76]}
              >
                <mesh
                  name="Subdiv1"
                  geometry={nodes.Subdiv1.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[-85.82, 94.41, 55.71]}
                  rotation={[-2.01, 0.42, -0.64]}
                  scale={[-0.37, 0.53, 0.65]}
                />
                <mesh
                  name="button"
                  geometry={nodes.button.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[86.62, 94.41, 55.71]}
                  rotation={[-2.01, -0.42, 0.64]}
                  scale={[0.37, 0.53, 0.65]}
                />
              </mesh>
              <mesh
                name="leg_r"
                geometry={nodes.leg_r.geometry}
                material={materials.Untitled}
                castShadow
                receiveShadow
                position={[-113.23, 7.94, 2.13]}
                rotation={[0.11, 0.12, -0.05]}
                scale={[0.94, 0.94, 0.98]}
              >
                <mesh
                  name="Torus"
                  geometry={nodes.Torus.geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[-13.28, -392.16, 23.42]}
                  rotation={[-1.57, 0, 0]}
                  scale={[0.26, 0.25, 0.14]}
                />
                <mesh
                  name="Torus 5"
                  geometry={nodes['Torus 5'].geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[0.76, -120.34, 1.08]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.26, 0.25, 0.18]}
                />
                <mesh
                  name="Subdiv2"
                  geometry={nodes.Subdiv2.geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[-131.73, -176.29, -3.51]}
                  rotation={[-1.56, -1.41, -1.56]}
                  scale={[0.57, 0.6, 0.37]}
                />
                <mesh
                  name="Subdiv3"
                  geometry={nodes.Subdiv3.geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[-2.05, -242.53, 119.4]}
                  rotation={[0, -0.02, 0]}
                  scale={[1.69, 0.27, 0.46]}
                />
                <mesh
                  name="boot_r"
                  geometry={nodes.boot_r.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, -276.28, -0.27]}
                  scale={[1.07, 1.07, 1.02]}
                />
              </mesh>
              <mesh
                name="leg_l"
                geometry={nodes.leg_l.geometry}
                material={materials.Untitled}
                castShadow
                receiveShadow
                position={[127.52, 7.97, 15.62]}
                rotation={[-0.05, -0.07, 0.03]}
                scale={[-0.94, 0.94, 0.98]}
              >
                <mesh
                  name="heart"
                  geometry={nodes.heart.geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[-131.32, -176.52, -3.51]}
                  rotation={[-Math.PI / 2, -1.43, -Math.PI / 2]}
                  scale={[-0.57, 0.6, 0.37]}
                />
                <mesh
                  name="knee_l"
                  geometry={nodes.knee_l.geometry}
                  material={materials.Untitled}
                  castShadow
                  receiveShadow
                  position={[-2.83, 5.95, 79.43]}
                  rotation={[0, -0.22, 0]}
                  scale={[1.08, 1.29, 1]}
                />
                <mesh
                  name="Torus1"
                  geometry={nodes.Torus1.geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[-7.74, -388.15, 12.33]}
                  rotation={[-1.57, 0, 0]}
                  scale={[-0.26, 0.25, 0.18]}
                />
                <mesh
                  name="Torus 4"
                  geometry={nodes['Torus 4'].geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[0.54, -120.34, 1.08]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[-0.26, 0.25, 0.18]}
                />
                <mesh
                  name="Cube2"
                  geometry={nodes.Cube2.geometry}
                  material={materials.Pants}
                  castShadow
                  receiveShadow
                  position={[1.71, -242.53, 119.84]}
                  rotation={[0, 0.02, 0]}
                  scale={[-1.69, 0.27, 0.46]}
                />
                <mesh
                  name="boot_l"
                  geometry={nodes.boot_l.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0.48, -276.28, -0.27]}
                  scale={[-1.07, 1.07, 1.02]}
                />
              </mesh>
            </group>
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[485, -65, 231]}
          />
          <group
            name="Empty Object"
            position={[228.69, -47.09, -94.75]}
            rotation={[0.34, -0.49, -0.33]}
            scale={[1.19, 1.38, 1.19]}
          >
            <group
              name="Empty Object 6"
              position={[63.64, 11.8, -29.96]}
              rotation={[-0.15, 0.33, -0.93]}
              scale={[1.6, 1.83, 2.47]}
            >
              <mesh
                name="Shape 10"
                geometry={nodes['Shape 10'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-44.51, -44.88, 29.29]}
                rotation={[-0.53, 0.02, 0.3]}
                scale={1}
              />
              <mesh
                name="Shape 9"
                geometry={nodes['Shape 9'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-50.98, -43.08, 25.89]}
                rotation={[-0.54, 0, 0.3]}
                scale={1}
              />
            </group>
            <group
              name="Empty Object 5"
              position={[-105.57, -55.61, 17.59]}
              rotation={[-2.95, 1.13, 1.33]}
              scale={[1.6, 1.83, 2.47]}
            >
              <mesh
                name="Shape 101"
                geometry={nodes['Shape 101'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-44.51, -46.42, 26.72]}
                rotation={[-0.53, 0.02, 0.3]}
                scale={1}
              />
              <mesh
                name="Shape 91"
                geometry={nodes['Shape 91'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-50.98, -43.08, 25.89]}
                rotation={[-0.54, 0, 0.3]}
                scale={1}
              />
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
